name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read

    env:
      PUSH_TO_DOCKER_HUB: ${{ vars.PUSH_TO_DOCKER_HUB }} 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        cd application \
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME }}:latest .
        

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME }}:latest
